### ISSUE TITLE
Usage of this crate ?

### ISSUE THREAD

**Issue by LeeMaster** [magnet/aspect-rs#1]
I'm a newbie in rust and I wanna using this project in my web project to control the permission on apis , But I don't know how to integrate this crate in my project

**Comment by magnet** [comment]
Hi LeeMaster,

I suggest you take a look at metered and try replacing the metrics system with your permissioning system.

The main benefit of aspect is that it abstracts over wrapping code whether sync or async, but it doesn't do much more than that, and this crate is mostly designed for library builders and not to be directly consumed by application developers.

**Comment by LeeMaster** [comment]
thx I will try it
